#!/usr/bin/env pytnon3

import os
from SCons.Script import Environment, Return

env = Environment(ENV = {
    "CFLAGS": "-std=c23",
    "PATH": os.environ["PATH"],
    "PKG_CONFIG_PATH": os.environ["PKG_CONFIG_PATH"],
})

# Dependencies by pkg-config
env.ParseConfig("pkg-config sdl3 --cflags --libs")

# Compile
program = env.Program(target = "foo-sdl3", source = "main.c")

Return("program")
