#!/usr/bin/env pytnon3

import os
from SCons.Script import Environment, Return

Import("env")

# Dependencies by pkg-config
env.ParseConfig("pkg-config sdl3 --cflags --libs")

# Compile
program = env.Program(target = "foo-sdl3", source = "main.c")

Return("program")
